# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-kwin.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-kwin.spec
    - .packit.yaml

upstream_ref: 5.2.0.13
upstream_package_name: dde-kwin
# downstream (Fedora) RPM package name
downstream_package_name: deepin-kwin

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-kwin.spec"
